version: "3.7"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3307:3306"

  php-apache:
    build: ./php
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  db_data: {}
